name: Deploy Azure Function

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend/api
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: talha-resume-func-2025
        package: backend/api
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
