name: Purge CDN Cache

# This workflow is triggered when the Frontend Deployment workflow completes successfully
on:
  workflow_run:
    workflows: ["Frontend Deployment"]
    types:
      - completed
  # Allow manual trigger as well
  workflow_dispatch:

# Environment variables
env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CDN_PROFILE_NAME: ${{ secrets.CDN_PROFILE_NAME }}
  CDN_ENDPOINT_NAME: ${{ secrets.CDN_ENDPOINT_NAME }}

jobs:
  purge:
    # Only run if the triggering workflow succeeded or this is manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      # Check out code for access to workflow scripts
      - uses: actions/checkout@v3

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FRONTEND_AZURE_CREDENTIALS }}

      # Purge CDN endpoint and verify status
      - name: Purge CDN Cache and Verify
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Purging CDN endpoint: ${{ env.CDN_ENDPOINT_NAME }}..."
            PURGE_ID=$(az cdn endpoint purge \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --profile-name ${{ env.CDN_PROFILE_NAME }} \
              --name ${{ env.CDN_ENDPOINT_NAME }} \
              --content-paths '/*' \
              --query id -o tsv)

            echo "✅ CDN purge operation initiated"
            echo "Purge ID: $PURGE_ID"

            RETRY_COUNT=0
            MAX_RETRIES=5

            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              echo "Verifying CDN endpoint is operational..."
              STATUS=$(az cdn endpoint show \
                --resource-group ${{ env.RESOURCE_GROUP }} \
                --profile-name ${{ env.CDN_PROFILE_NAME }} \
                --name ${{ env.CDN_ENDPOINT_NAME }} \
                --query "resourceState" -o tsv)
                
              echo "Current endpoint status: $STATUS"
              
              if [[ "$STATUS" == "Running" ]]; then
                echo "✅ CDN endpoint is running properly!"
                exit 0
              else
                echo "⏳ Waiting for CDN endpoint to stabilize..."
                sleep 15
              fi
              
              RETRY_COUNT=$((RETRY_COUNT+1))
              
              if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
                echo "⚠️ Reached maximum retry attempts. Check Azure Portal for final status."
                # Don't fail the workflow as the purge might still be processing
                exit 0
              fi
            done
